import { API_PATH } from 'yeppi-common';

const prefix: string = '';

const MerchantRoutes = {
	MerchantInfo: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.INFO}/many`,
		SaveMany: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.INFO}/update`,
	},
	Images: {
		Upload: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.IMAGES}/upload`,
		UploadMultiple: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.IMAGES}/upload-multiple`,
	},
	Auth: {
		Heartbeat: () => `${prefix}/${API_PATH.MERCHANT}/heartbeat`,
		Login: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AUTH}/login`,
		Refresh: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AUTH}/refresh`,
		Verify: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AUTH}/verify`,
		Logout: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AUTH}/logout`,
		PasswordReset: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AUTH}/password-reset`,
		PasswordResetValidate: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AUTH}/password-reset-validate`,
		PasswordResetConfirm: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AUTH}/password-reset-confirm`,
	},
	Countries: {
		Single: (iso2: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.COUNTRIES}/${iso2}`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.COUNTRIES}/many`,
		Update: (iso2: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.COUNTRIES}/${iso2}`,
	},
	Currencies: {
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CURRENCIES}/${code}`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CURRENCIES}/many`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CURRENCIES}/${code}`,
	},
	Customers: {
		Single: (cust_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CUSTOMERS}/${cust_no}`,
		Orders: (cust_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CUSTOMERS}/${cust_no}/orders`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CUSTOMERS}/many`,
		UpdateInsights: (cust_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CUSTOMERS}/${cust_no}/insights`,
		Import: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CUSTOMERS}/import`,
		ImportTemplate: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CUSTOMERS}/import/template`,
	},
	Products: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD}/create`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD}/${code}`,
		BySlug: (slug: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD}/by-slug/${encodeURIComponent(slug)}`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD}/many`,
		Import: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD}/import`,
		ImportTemplate: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD}/import/template`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD}/${code}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD}/${code}`,
		DeleteVariant: (code: string, variant_code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD}/${code}/variants/${variant_code}`,
		Restore: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD}/restore/${code}`,
	},
	ProductBrands: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_BRANDS}/create`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_BRANDS}/${code}`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_BRANDS}/many`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_BRANDS}/${code}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_BRANDS}/${code}`,
		Restore: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_BRANDS}/restore/${code}`,
	},
	ProductTags: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TAGS}/create`,
		Single: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TAGS}/${id}`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TAGS}/many`,
		Update: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TAGS}/${id}`,
		Delete: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TAGS}/${id}`,
		Restore: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TAGS}/restore/${id}`,
	},
	ProductTypes: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TYPES}/create`,
		Single: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TYPES}/${id}`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TYPES}/many`,
		Update: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TYPES}/${id}`,
		Delete: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TYPES}/${id}`,
		Restore: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_TYPES}/restore/${id}`,
	},
	ProductCategories: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_CATEGORIES}/create`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_CATEGORIES}/${code}`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_CATEGORIES}/many`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_CATEGORIES}/${code}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_CATEGORIES}/${code}`,
		Restore: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_CATEGORIES}/restore/${code}`,
	},
	ProdVariations: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_VARIATIONS}/create`,
		Single: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_VARIATIONS}/${id}`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_VARIATIONS}/many`,
		Update: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_VARIATIONS}/${id}`,
		Delete: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_VARIATIONS}/${id}`,
		Restore: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_VARIATIONS}/restore/${id}`,
	},
	ProdVariants: {
		// Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_VARIANTS}/create`,
		SingleByProdCode: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_VARIANTS}/${code}`,
		// Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_VARIANTS}/many`,
		// Update: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_OPTIONS}/${id}`,
		// Delete: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_VARIANTS}/${id}`,
		// Restore: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PROD_VARIANTS}/restore/${id}`,
	},
	Settings: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SETTINGS}/many`,
		SaveMany: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SETTINGS}/update`,
	},
	CrmUsers: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CRM_USERS}/create`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CRM_USERS}/many`,
		Single: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CRM_USERS}/${id}`,
		Update: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CRM_USERS}/${id}`,
		UpdatePassword: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CRM_USERS}/${id}/password`,
		ResetPassword: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CRM_USERS}/${id}/reset-password`,
		Delete: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CRM_USERS}/${id}`,
		Restore: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.CRM_USERS}/restore/${id}`,
	},
	StaffCommissions: {
		Departments: () => `${prefix}/${API_PATH.MERCHANT}/staff-commissions/departments`,
		Department: (id: number) => `${prefix}/${API_PATH.MERCHANT}/staff-commissions/departments/${id}`,
		DepartmentCreate: () => `${prefix}/${API_PATH.MERCHANT}/staff-commissions/departments`,
		DepartmentUpdate: (id: number) => `${prefix}/${API_PATH.MERCHANT}/staff-commissions/departments/${id}`,
		DepartmentDelete: (id: number) => `${prefix}/${API_PATH.MERCHANT}/staff-commissions/departments/${id}`,
	},
	Orders: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.ORDERS}/many`,
		Single: (order_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.ORDERS}/${order_no}`,
		Update: (order_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.ORDERS}/${order_no}/update`,
		UpdateOrderStatus: (order_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.ORDERS}/${order_no}/status`,
		UpdateOrderCustomer: (order_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.ORDERS}/${order_no}/customer`,
		UpdateOrderItems: (order_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.ORDERS}/${order_no}/items`,
		UpdateOrderPayments: (order_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.ORDERS}/${order_no}/payments`,
		ResendEmail: (order_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.ORDERS}/${order_no}/resend-email`,
		Process: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.ORDERS}/process`,
		Export: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.ORDERS}/export`,
	},
	Notifications: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.NOTIFICATIONS}/many`,
		Read: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.NOTIFICATIONS}/${id}/read`,
		Open: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.NOTIFICATIONS}/${id}/open`,
	},
	ActivityLogs: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/activity-logs/many`,
	},
	Sales: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SALES}/many`,
		Single: (order_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SALES}/${order_no}`,
		UpdateOrderStatus: (order_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SALES}/${order_no}/status`,
		ResendEmail: (order_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SALES}/${order_no}/resend-email`,
		Process: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SALES}/process`,
		Export: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SALES}/export`,
	},
	SummOrders: {
		Dashboard: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_ORDERS}/dashboard`,
		Orders: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_ORDERS}/orders`,
		Export: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_ORDERS}/export`,
		Items: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_ORDERS}/items`,
		ExportItems: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_ORDERS}/items/export`,
		Customers: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_ORDERS}/customers`,
		ExportCustomers: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_ORDERS}/customers/export`,
	},
	SummSales: {
		Dashboard: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_SALES}/dashboard`,
		Sales: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_SALES}/sales`,
		Export: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_SALES}/export`,
		Items: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_SALES}/items`,
		ExportItems: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_SALES}/items/export`,
		Customers: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_SALES}/customers`,
		ExportCustomers: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_SALES}/customers/export`,
		Payments: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_SALES}/payments`,
		ExportPayments: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SUMM_SALES}/payments/export`,
	},
	PaymentTypes: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PAYMENT_TYPES}/many`,
	},
	PaymentTypeGroups: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PAYMENT_TYPE_GROUPS}/many`,
	},
	PaymentMethods: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PAYMENT_METHODS}/many`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.PAYMENT_METHODS}/${code}`,
	},
	Appointments: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.APPOINTMENTS}/create`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.APPOINTMENTS}/${code}`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.APPOINTMENTS}/many`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.APPOINTMENTS}/${code}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.APPOINTMENTS}/${code}`,
		Restore: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.APPOINTMENTS}/restore/${code}`,
		GetByCustomer: (customer_no: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.APPOINTMENTS}/customer/${customer_no}`,
	},
	Outlets: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.OUTLETS}/create`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.OUTLETS}/many`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.OUTLETS}/${code}`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.OUTLETS}/${code}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.OUTLETS}/${code}`,
		Restore: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.OUTLETS}/restore/${code}`,
	},
	Taxes: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAXES}/create`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAXES}/many`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAXES}/${code}`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAXES}/${code}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAXES}/${code}`,
		Restore: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAXES}/restore/${code}`,
	},
	TaxGroups: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_GROUPS}/create`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_GROUPS}/many`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_GROUPS}/${code}`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_GROUPS}/${code}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_GROUPS}/${code}`,
		Restore: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_GROUPS}/restore/${code}`,
	},
	TaxRules: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_RULES}/create`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_RULES}/many`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_RULES}/${code}`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_RULES}/${code}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_RULES}/${code}`,
		Restore: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.TAX_RULES}/restore/${code}`,
	},
	Discounts: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.DISCOUNTS}/create`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.DISCOUNTS}/many`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.DISCOUNTS}/${code}`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.DISCOUNTS}/${code}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.DISCOUNTS}/${code}`,
		Restore: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.DISCOUNTS}/restore/${code}`,
	},
	Vouchers: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.VOUCHERS}/create`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.VOUCHERS}/many`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.VOUCHERS}/${code}`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.VOUCHERS}/${code}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.VOUCHERS}/${code}`,
	},
	Affiliates: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AFFILIATES}`,
		BySlug: (slug: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AFFILIATES}/by-slug/${slug}`,
		Single: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AFFILIATES}/${id}`,
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AFFILIATES}`,
		Tiers: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AFFILIATES}/tiers`,
		TierCreate: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AFFILIATES}/tiers`,
		TierUpdate: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AFFILIATES}/tiers/${id}`,
		TierDelete: (id: number) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AFFILIATES}/tiers/${id}`,
		MyReport: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.AFFILIATES}/my-report`,
	},
	Fulfillment: {
		Create: (order_no: string) => `${prefix}/${API_PATH.MERCHANT}/fulfillment/${order_no}/create`,
		Update: (id: string) => `${prefix}/${API_PATH.MERCHANT}/fulfillment/${id}`,
		MarkProcessing: (id: string) => `${prefix}/${API_PATH.MERCHANT}/fulfillment/${id}/processing`,
		MarkPacked: (id: string) => `${prefix}/${API_PATH.MERCHANT}/fulfillment/${id}/packed`,
		MarkFulfilled: (id: string) => `${prefix}/${API_PATH.MERCHANT}/fulfillment/${id}/fulfilled`,
		MarkShipped: (id: string) => `${prefix}/${API_PATH.MERCHANT}/fulfillment/${id}/shipped`,
		MarkDelivered: (id: string) => `${prefix}/${API_PATH.MERCHANT}/fulfillment/${id}/delivered`,
	},
	/** Server-side Nominatim proxy (OpenStreetMap); no extra API key. */
	Geocode: {
		Search: () => `${prefix}/${API_PATH.MERCHANT}/geocode/search`,
	},
	Couriers: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.COURIERS}/many`,
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.COURIERS}/create`,
		Single: (id: number | string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.COURIERS}/${id}`,
		Update: (id: number | string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.COURIERS}/${id}`,
		Delete: (id: number | string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.COURIERS}/${id}`,
	},
	ShippingMethods: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SHIPPING_METHODS}/many`,
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SHIPPING_METHODS}/create`,
		Resolve: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SHIPPING_METHODS}/resolve`,
		Single: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SHIPPING_METHODS}/${id}`,
		Update: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SHIPPING_METHODS}/${id}`,
		Delete: (id: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SHIPPING_METHODS}/${id}`,
	},
	ShippingZones: {
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SHIPPING_ZONES}/many`,
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SHIPPING_ZONES}`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SHIPPING_ZONES}/${encodeURIComponent(code)}`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SHIPPING_ZONES}/${encodeURIComponent(code)}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.SHIPPING_ZONES}/${encodeURIComponent(code)}`,
	},
	Reasons: {
		Create: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.REASONS}/create`,
		Many: () => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.REASONS}/many`,
		Single: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.REASONS}/${encodeURIComponent(code)}`,
		Update: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.REASONS}/${encodeURIComponent(code)}`,
		Delete: (code: string) => `${prefix}/${API_PATH.MERCHANT}/${API_PATH.REASONS}/${encodeURIComponent(code)}`,
	},
};

export default MerchantRoutes;
