import type { OrderStatus, OrderType, PaymentStatus } from 'yeppi-common';
import type { TaxModel } from '../models/tax.model';
import type { Currency } from './currency';
import type { ItemModel, PaymentModel, CustomerModel } from '../models';
import type { FulfillmentBatch } from './order-fulfillment-shipping';

export type Bill = {
	biz_date: string;
	order_no: string;
	inv_no: string;
	order_date_time: Date;
	customer_no: string;
	status: OrderStatus;
	payment_status: PaymentStatus;
	gross_amt: number;
	net_amt: number;
	net_total: number;
	shipping_fee: number;
	payable_total: number;
	disc_amt: number;
	gross_amt_exc: number;
	net_amt_exc: number;
	disc_amt_exc: number;
	tax_amt_exc: number;
	void_amt: number;
	adj_amt: number;
	total_item_qty: number;
	voided_qty: number;
	ref_no: string;
	remarks: string;
	order_type: OrderType;
	currency: Currency;
	fulfillments: FulfillmentBatch[];
	items: ItemModel[];
	payments: PaymentModel[];
	customer: CustomerModel;
	taxes: TaxModel[];
};
